package com.myspace.pruebatres;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity 
@javax.persistence.Table(name = "pruebaTres")

public class persistencia implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PERSISTENCIA_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "PERSISTENCIA_ID_GENERATOR", sequenceName = "PERSISTENCIA_ID_SEQ")
	
	private java.lang.Long id;

	private java.lang.String nombre;

	private java.lang.String motivo;

	public persistencia() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getNombre() {
		return this.nombre;
	}

	public void setNombre(java.lang.String nombre) {
		this.nombre = nombre;
	}

	public java.lang.String getMotivo() {
		return this.motivo;
	}

	public void setMotivo(java.lang.String motivo) {
		this.motivo = motivo;
	}

	public persistencia(java.lang.Long id, java.lang.String nombre,
			java.lang.String motivo) {
		this.id = id;
		this.nombre = nombre;
		this.motivo = motivo;
	}

}